package headless

import (
	"fmt"
	"io"
	"maps"
	"slices"
	"strings"

	"sstui/poller"
	"sstui/session"
)

// WriteMarkdown writes an incident summary: what was watched, a timeline of
// every finding, each finding in full, the host counters that moved, the
// sockets at the end, and the kernel settings the advice was based on. It
// is meant to be pasted into a ticket or a chat as is.
func WriteMarkdown(w io.Writer, tl *session.Timeline, m Meta) {
	p := func(format string, a ...any) { fmt.Fprintf(w, format, a...) }
	status, _ := Status(tl)

	p("# Network report: %s\n\n", m.Host)
	p("| | |\n|---|---|\n")
	p("| Status | **%s**: %s |\n", status, counts(tl))
	host := m.Host
	if m.Kernel != "" {
		host += " (Linux " + m.Kernel + ")"
	}
	p("| Host | %s |\n", cell(host))
	if tl.Analyses > 0 {
		p("| Window | %s → %s, %s every %s |\n", tl.Start.Format("2006-01-02 15:04:05"), tl.End.Format("15:04:05"),
			window(tl), m.Interval)
	}
	if m.Source == "live" {
		p("| Source | live |\n")
	} else {
		p("| Source | recording `%s` |\n", cell(m.Source))
	}
	if m.SSFilter != "" {
		p("| ss filter | `%s` (socket checks see only matching sockets; kernel counters stay host-wide) |\n", cell(m.SSFilter))
	}
	p("| Generated by | sstui %s |\n\n", m.Version)

	if n := tl.Last.HiddenProcs; n > 0 {
		p("> Not run as root: process names were hidden for %s owned by other users.\n\n", plural(n, "socket"))
	}
	if m.Failed > 0 {
		p("> %s failed (last error: `%v`).\n\n", plural(m.Failed, "poll"), m.LastErr)
	}
	if m.Unclosed {
		p("> The recording wasn't closed cleanly (sstui was killed); every complete poll in it was analysed.\n\n")
	}
	if tl.Analyses == 0 {
		p("No polls completed, so there is nothing to analyse.\n")
		return
	}

	ranked := tl.Ranked()
	p("## Summary\n\n")
	if len(ranked) == 0 {
		p("No problems were detected. %d sockets (%d established) at the end", tl.Last.Sockets, tl.Last.Estab)
		if tl.Last.RetransPct >= 0 {
			p(", host retransmits %.2f%%", tl.Last.RetransPct)
		}
		p(".\n\n")
	} else {
		p("| Severity | Finding | First seen | Last seen | Polls | At the end |\n|---|---|---|---|---|---|\n")
		for _, o := range ranked {
			end := "resolved"
			if o.Active {
				end = "**active**"
			}
			p("| %s | %s | %s | %s | %d of %d | %s |\n", sevName(o.Worst), cell(o.Finding.Title),
				o.First.Format("15:04:05"), o.Last.Format("15:04:05"), o.Polls, tl.Analyses, end)
		}
		p("\n## Findings\n\n")
		for _, o := range ranked {
			writeFinding(w, o, tl, m)
		}
	}

	writeCounters(w, tl, m)
	writeSockets(w, m)
	writeSysctls(w, m)
}

func writeFinding(w io.Writer, o *session.Occurrence, tl *session.Timeline, m Meta) {
	p := func(format string, a ...any) { fmt.Fprintf(w, format, a...) }
	f := o.Finding
	p("### %s: %s\n\n", strings.ToUpper(sevName(o.Worst)), f.Title)
	p("%s\n\n", f.Detail)
	p("*%s.*\n\n", capitalize(seen(o, tl)))
	if len(f.Evidence) > 0 {
		p("**Evidence** (at the last poll it was seen):\n\n")
		for _, e := range f.Evidence {
			p("- %s\n", e)
		}
		p("\n")
	}
	if len(f.Actions) > 0 {
		p("**What to do:**\n\n")
		for i, a := range f.Actions {
			p("%d. %s\n", i+1, a.Text)
			if a.Command != "" {
				p("   ```sh\n   %s\n   ```\n", a.Command)
			}
		}
		p("\n")
	}
	if cmd := socketsCommand(o, m); cmd != "" {
		p("**Affected sockets** (%d): `%s`\n\n", f.Count, cmd)
	}
}

// writeCounters lists the host counters that moved during the window.
func writeCounters(w io.Writer, tl *session.Timeline, m Meta) {
	first, last := tl.FirstSys, tl.LastSys
	if first == nil || last == nil || first == last {
		return
	}
	secs := last.Timestamp.Sub(first.Timestamp).Seconds()
	var rows []string
	for _, g := range poller.CounterGroups {
		for _, c := range g.Counters {
			d, ok := last.Delta(first, c.Key)
			if !ok || d == 0 {
				continue
			}
			label := c.Label
			if c.Alert {
				label = "⚠ " + label
			}
			rate := ""
			if secs > 0 {
				rate = fmt.Sprintf("%.1f", float64(d)/secs)
			}
			rows = append(rows, fmt.Sprintf("| %s | %s | %d | %s |", g.Title, label, d, rate))
		}
	}
	if len(rows) == 0 {
		return
	}
	fmt.Fprintf(w, "## Host counters\n\nIncrease over the window (`/proc/net/snmp`, `/proc/net/netstat`). ⚠ marks counters where any increase is a problem.\n\n")
	fmt.Fprintf(w, "| Group | Counter | Increase | Per second |\n|---|---|---|---|\n%s\n", strings.Join(rows, "\n"))
	if out, ok := last.Delta(first, "Tcp:OutSegs"); ok && out > 0 {
		re, _ := last.Delta(first, "Tcp:RetransSegs")
		fmt.Fprintf(w, "\nTCP retransmit rate over the window: **%.2f%%** (%d of %d segments).\n", float64(re)/float64(out)*100, re, out)
	}
	fmt.Fprintln(w)
}

// writeSockets summarises the sockets at the last poll.
func writeSockets(w io.Writer, m Meta) {
	if len(m.Final) == 0 {
		return
	}
	fmt.Fprintf(w, "## Sockets at the end\n\n| State | Sockets |\n|---|---|\n")
	for _, e := range stateCounts(m.Final) {
		fmt.Fprintf(w, "| %s | %d |\n", e.k, e.v)
	}
	fmt.Fprintf(w, "\n| Process | Sockets |\n|---|---|\n")
	for _, e := range topProcesses(m.Final, 10) {
		fmt.Fprintf(w, "| %s | %d |\n", cell(e.k), e.v)
	}
	fmt.Fprintln(w)
}

// writeSysctls lists the kernel settings the recommendations reasoned about.
func writeSysctls(w io.Writer, m Meta) {
	if len(m.Sysctl) == 0 {
		return
	}
	fmt.Fprintf(w, "## Kernel settings\n\n| Setting | Value |\n|---|---|\n")
	for _, k := range slices.Sorted(maps.Keys(m.Sysctl)) {
		fmt.Fprintf(w, "| %s | `%s` |\n", k, cell(m.Sysctl[k]))
	}
	fmt.Fprintln(w)
}

// cell escapes text for a markdown table cell.
func cell(s string) string {
	return strings.ReplaceAll(strings.ReplaceAll(s, "|", `\|`), "\n", " ")
}

func capitalize(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}
